name: PIV_test
channels:
  - nvidia
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=openblas
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.4.0=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py311h5eee18b_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - gcc=12.1.0=h9ea6d83_10
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.38=hd590300_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=70.1=h27087fc_0
  - imagecodecs=2023.1.23=py311h8105a5c_0
  - imageio=2.33.1=py311h06a4308_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.31.0=py311h7040dfc_0
  - ipython=8.15.0=py311h06a4308_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.18.1=py311h06a4308_1
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - jupyterlab_widgets=3.0.15=py311h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.4.5.8=0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.7.1=h251f7ec_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_1
  - libdrm=2.4.121=h4ab18f5_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=12.3.0=h77fa898_13
  - libgcrypt=1.10.3=hd590300_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=12.3.0=h77fa898_13
  - libgpg-error=1.49=h4f305b6_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopencv=4.7.0=py311h7a0761e_1
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsanitizer=12.1.0=ha89aaad_17
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=12.3.0=hc0a3c3a_13
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.8.4=py311ha02d727_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mpg123=1.32.6=h59595ed_0
  - multiprocess=0.70.16=py311h459d7ec_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - opencv=4.7.0=py311h38be061_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.1.6=h4ab18f5_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.1=py311h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py311h5eee18b_0
  - pip=23.3=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py311h781c19f_1
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.0.9=py311h06a4308_0
  - python=3.11.0=he550d4f_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.11=4_cp311
  - pyzmq=25.1.0=py311h6a678d5_0
  - qt-main=5.15.8=h5d23da1_6
  - readline=8.2=h5eee18b_0
  - scikit-image=0.23.2=py311ha02d727_0
  - scipy=1.13.1=py311h24aa872_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tifffile=2023.4.12=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.4=py311h92b7b1e_0
  - traitlets=5.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py311h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_0
  - pip:
      - appdirs==1.4.4
      - colorama==0.4.6
      - comm==0.2.2
      - h5py==3.12.1
      - hdf5storage==0.1.19
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - llvmlite==0.43.0
      - mako==1.3.5
      - markupsafe==2.1.5
      - modulo-vki==2.0.7
      - nose==1.3.7
      - numba==0.60.0
      - openpiv==0.0.0
      - py==1.11.0
      - pycuda==2024.1
      - pymraw==0.32
      - pytools==2024.1.5
      - scikit-cuda==0.5.4
      - scikit-learn==1.5.2
      - threadpoolctl==3.5.0
      - transformations==2024.5.24
      - widgetsnbextension==4.0.13
      - xmltodict==0.13.0
